import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

// Explicitly define the type for metadata
interface CustomMetadata extends Metadata {
  title: string;
  description: string;
}

const metadata: CustomMetadata = {
  title: 'My-CV-Generator',
  description: 'Generated by create next app',
};

const Header = () => {
  return (
      <header className="bg-blue-500 text-white py-4">
        <div className="container mx-auto">
          <h1 className="text-2xl font-semibold">My CV Generator</h1>
        </div>
      </header>
  );
};

const Footer = () => {
  return (
      <footer className="bg-blue-500 text-white py-4">
        <div className="container mx-auto text-center">
          <p>© {new Date().getFullYear()} My Cool Next.js App. All rights reserved.</p>
        </div>
      </footer>
  );
};

const Navigation = () => {
  return (
      <nav className="bg-gray-200 p-4">
        <div className="container mx-auto flex justify-between items-center">
          <ul className="flex space-x-4">
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/about">About</a>
            </li>
            <li>
              <a href="/contact">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
  );
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`font-sans ${inter.className}`}>
      <Header />
      <Navigation />
      <main>{children}</main>
      <Footer />
      </body>
      </html>
  );
}